services:
  database_estudai:
    image: postgres
    container_name: database.usjt-clinic
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=usjt-clinic
    volumes:
      - postgres:/var/lib/postgresql/data
    network_mode: "host"
  app:
    build: .
    container_name: clinic
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: "host"

volumes:
  postgres:
    driver: local